name: GoldenCheetah GitHub Actions
run-name: ${{ github.actor }} for GoldenCheetah
on: [push]
jobs:
  Build-Linux:
    runs-on: ubuntu-24.04
    if: false
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - name: Install Qt6 and other dependencies
        run: >
          sudo apt install \
            qt6-base-dev \
            qt6-charts-dev \
            qt6-multimedia-dev \
            qt6-serialport-dev \
            qt6-svg-dev \
            qt6-webchannel-dev \
            qt6-webengine-dev \
            qt6-positioning-dev \
            qt6-connectivity-dev \
            qt6-5compat-dev \
            qt6-l10n-tools \
            libgsl-dev \
            libsamplerate0-dev \
            libusb-1.0-0-dev \
            libical-dev \
            libfuse2
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Prepare Qwt Config
        run: >
          cd ${{ github.workspace }}/qwt;
          cp qwtconfig.pri.in qwtconfig.pri
      - name: Prepare GoldenCheetah Config
        run: >
          cp ${{ github.workspace }}/gha/linux/gcconfig.pri ${{ github.workspace }}/src/gcconfig.pri
      - name: Enable Unittests
        run: >
          cd ${{ github.workspace }}/unittests;
          cp unittests.pri.in unittests.pri
      - name: Generate Makefiles
        run: |
          qmake6 -r ${{ github.workspace }}
      - name: Build
        run: >
          export MAKEFLAGS="-j $(nproc) --output-sync=target";
          cd ${{ github.workspace }};
          make
      - name: Run Unittests
        run: >
          export QT_QPA_PLATFORM=minimal;
          export MAKEFLAGS="-j $(nproc) --output-sync=target";
          cd ${{ github.workspace }};
          make check
      - name: Publish GoldenCheetah Binary
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah Binary
          path: src/GoldenCheetah
          retention-days: 5
      - name: Create GoldenCheetah AppImage
        run: >
          cd ${{ github.workspace }};
          ./gha/linux/after_success.sh
      - name: Publish GoldenCheetah AppImage
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah AppImage
          path: src/GoldenCheetah_*.AppImage
          retention-days: 5
      - name: Publish GoldenCheetah Versionfile
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah Versionfile
          path: src/GCversionLinux.txt
          retention-days: 5
      - run: echo "This job's status is ${{ job.status }}"
