name: GoldenCheetah GitHub Actions (MacOS)
run-name: ${{ github.actor }} for GoldenCheetah (MacOS)
on: [push]
env:
  GC_VERSION: v3.7
  QT_VERSION: 6.8.3
jobs:
  Build-MacOS-arm64-aqt:
    runs-on: macos-14
    if: true
    env:
      ARCH: arm64
      FINAL_NAME: GoldenCheetah_${{ env.GC_VERSION }}_${{ env.ARCH }}-aqt.dmg
    steps:
      - run: >
          echo "Building ${{ github.ref }} @ ${{ github.repository }} " \
            "triggered by ${{ github.actor }} with ${{ github.event_name }} " \
            "on ${{ runner.os }}"
      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: mac
          modules: 'qtserialport qtmultimedia qtwebengine qtwebengine qtwebchannel qtpositioning qt5compat qtconnectivity qtcharts'
      - name: Install other dependencies
        run: >
          brew install \
            gsl \
            bison
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare Qwt Config
        run: >
          cd ${{ github.workspace }}/qwt;
          cp qwtconfig.pri.in qwtconfig.pri
      - name: Prepare GoldenCheetah Config
        run: >
          cp ${{ github.workspace }}/gha/macos-${{ env.ARCH }}/gcconfig.pri ${{ github.workspace }}/src/gcconfig.pri
      - name: Generate Makefiles
        run: |
          qmake6 -r ${{ github.workspace }}
      - name: Build
        run: >
          export PATH="$(brew --prefix bison)/bin:$PATH";
          cd ${{ github.workspace }};
          make
      - name: Add dependencies
        run: >
          cd ${{ github.workspace }};
          ./gha/macos-${{ env.ARCH }}/after_success.sh
      - name: Publish GoldenCheetah binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_NAME }}
          path: src/GoldenCheetah.dmg
      - name: Publish GoldenCheetah version
        uses: actions/upload-artifact@v4
        with:
          name: GCversionMacOS-${{ env.ARCH }}.txt
          path: src/GCversionMacOS.txt
      - run: echo "Finished with status ${{ job.status }}"
  Build-MacOS-arm64:
    runs-on: macos-14
    if: false
    steps:
      - run: >
          echo "Building ${{ github.ref }} @ ${{ github.repository }} " \
            "triggered by ${{ github.actor }} with ${{ github.event_name }} " \
            "on ${{ runner.os }}"
      - name: Install Qt6 and other dependencies
        run: >
          brew install \
            qt@6 \
            gsl \
            bison
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare Qwt Config
        run: >
          cd ${{ github.workspace }}/qwt;
          cp qwtconfig.pri.in qwtconfig.pri
      - name: Prepare GoldenCheetah Config
        run: >
          cp ${{ github.workspace }}/gha/macos-arm64/gcconfig.pri ${{ github.workspace }}/src/gcconfig.pri
      - name: Generate Makefiles
        run: |
          qmake6 -r ${{ github.workspace }}
      - name: Build
        if: false
        run: >
          export PATH=/opt/homebrew/opt/bison/bin:$PATH;
          cd ${{ github.workspace }};
          make
      - name: Add dependencies
        run: >
          cd ${{ github.workspace }};
          ./gha/macos-arm64/after_success.sh
      - name: Publish GoldenCheetah binary
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah-arm64
          path: src/GoldenCheetah.app
      - run: echo "Finished with status ${{ job.status }}"
  Build-MacOS-intel:
    runs-on: macos-13
    if: false
    env:
      FINAL_NAME: GoldenCheetah_v3.7_x64-gha.dmg
    steps:
      - run: >
          echo "Building ${{ github.ref }} @ ${{ github.repository }} " \
            "triggered by ${{ github.actor }} with ${{ github.event_name }} " \
            "on ${{ runner.os }}"
      - name: Install Qt5 and other dependencies
        run: >
          brew install \
            qt@5 \
            gsl \
            bison \
            tree
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare Qwt Config
        run: >
          cd ${{ github.workspace }}/qwt;
          cp qwtconfig.pri.in qwtconfig.pri
      - name: Prepare GoldenCheetah Config
        run: >
          cp ${{ github.workspace }}/gha/macos-intel/gcconfig.pri ${{ github.workspace }}/src/gcconfig.pri
      - name: Generate Makefiles
        run: |
          export PATH="$(brew --prefix qt@5)/bin:$PATH"
          qmake -r ${{ github.workspace }}
      - name: Build
        if: false
        run: >
          export PATH="$(brew --prefix bison)/bin:$PATH";
          cd ${{ github.workspace }};
          make
      - name: Publish GoldenCheetah binary (#1)
        if: false
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah-intel-buildonly
          path: src/GoldenCheetah.app
      - name: Pseudobuild
        if: true
        run: |
          export PATH="$(brew --prefix tree)/bin:$PATH"
          mkdir ${{ github.workspace }}/src/GoldenCheetah.app
          cd ${{ github.workspace }}/src
          wget https://gc.soschee.net/GoldenCheetah-intel-buildonly.zip
          cd ${{ github.workspace }}/src/GoldenCheetah.app
          unzip ../GoldenCheetah-intel-buildonly.zip
          tree .
      - name: Add dependencies
        run: |
          pwd
          echo ${{ github.workspace }}
          export PATH="$(brew --prefix qt@5)/bin:$PATH"
          cd ${{ github.workspace }}
          ./gha/macos-intel/after_success.sh
      - name: Publish GoldenCheetah binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_NAME }}
          path: src/GoldenCheetah.dmg
      - name: Publish GoldenCheetah version
        uses: actions/upload-artifact@v4
        with:
          name: GCversionMacOS.txt
          path: src/GCversionMacOS-x64.txt
      - run: echo "Finished with status ${{ job.status }}"
